begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select extensions.plan(16);
select extensions.ok(has_table_privilege('authenticated','public.accounts','SELECT'),'accounts remain readable');
select extensions.ok(has_table_privilege('authenticated','public.holdings','SELECT'),'holdings remain readable');
select extensions.ok(has_table_privilege('authenticated','public.instruments','SELECT'),'instruments remain readable');
select extensions.ok(has_table_privilege('authenticated','public.tags','SELECT'),'asset tags remain readable');
select extensions.ok(not has_table_privilege('authenticated','public.accounts','INSERT'),'accounts direct insert denied');
select extensions.ok(not has_table_privilege('authenticated','public.holdings','INSERT'),'holdings direct insert denied');
select extensions.ok(not has_table_privilege('authenticated','public.instruments','INSERT'),'instruments direct insert denied');
select extensions.ok(not has_table_privilege('authenticated','public.tags','INSERT'),'asset tags direct insert denied');
select extensions.ok(not has_table_privilege('authenticated','public.accounts','UPDATE'),'accounts direct update denied');
select extensions.ok(not has_table_privilege('authenticated','public.holdings','UPDATE'),'holdings direct update denied');
select extensions.ok(not has_table_privilege('authenticated','public.instruments','UPDATE'),'instruments direct update denied');
select extensions.ok(not has_table_privilege('authenticated','public.tags','UPDATE'),'asset tags direct update denied');
select extensions.ok(not has_table_privilege('authenticated','public.accounts','DELETE'),'accounts direct delete denied');
select extensions.ok(not has_table_privilege('authenticated','public.holdings','DELETE'),'holdings direct delete denied');
select extensions.ok(not has_table_privilege('authenticated','public.instruments','DELETE'),'instruments direct delete denied');
select extensions.ok(not has_table_privilege('authenticated','public.tags','DELETE'),'asset tags direct delete denied');
select * from extensions.finish();
rollback;
