import { expect, test } from '@playwright/test'
import { callRpc, clickPageAction, signInAs } from './helpers'

test('validates upper fields by Unicode code points without clipping input', async ({ page }) => {
  await signInAs(page, 'e2e-owner@example.com')
  await page.goto('/#tasks')
  await clickPageAction(page, '할 일과 기록', '활동 추가')
  const editor = page.getByRole('dialog', { name: '활동 추가' })
  await editor.getByLabel('이미 했음').check()
  const title = editor.getByRole('textbox', { name: '기록 제목', exact: true })
  const summary = editor.getByRole('textbox', { name: '요약', exact: true })
  const save = editor.getByRole('button', { name: '저장', exact: true })
  await title.fill('😀'.repeat(101))
  await summary.fill('한'.repeat(300))
  await editor.getByLabel('기록 내용').fill('Unicode 경계 검증 상세')
  await expect(title).toHaveValue('😀'.repeat(101))
  await expect(editor.getByRole('alert')).toContainText('101자')
  await expect(save).toBeDisabled()
  await title.fill('😀'.repeat(100))
  await summary.fill('😀'.repeat(301))
  await expect(editor.getByRole('alert')).toContainText('301자')
  await expect(save).toBeDisabled()
  await summary.fill('😀'.repeat(300))
  await expect(save).toBeEnabled()
  await save.click()
  await expect(editor).toBeHidden()
  const row = page.getByRole('listitem').filter({ hasText: '😀'.repeat(100) }).first()
  await expect(row).toContainText('😀'.repeat(300))
  await expect(row).not.toContainText('Unicode 경계 검증 상세')
})

test('writes upper fields separately and reveals the body only in detail', async ({ page }) => {
  await signInAs(page, 'e2e-owner@example.com')
  await page.goto('/#tasks')
  const title = `E2E 구조화 기록 ${Date.now()}`
  const summary = '대출 조건 미확정으로 추가 매수를 보류했다. 조건 확정 후 상환 현금을 재검토한다.'
  const sentinel = `본문전용-${Date.now()}`
  await clickPageAction(page, '할 일과 기록', '활동 추가')
  const editor = page.getByRole('dialog', { name: '활동 추가' })
  await editor.getByLabel('이미 했음').check()
  await editor.getByRole('textbox', { name: '기록 제목' }).fill(title)
  const save = editor.getByRole('button', { name: '저장', exact: true })
  await expect(save).toBeDisabled()
  await editor.getByRole('textbox', { name: '요약', exact: true }).fill(summary)
  await expect(save).toBeDisabled()
  await editor.getByLabel('기록 내용').fill(`## 상세 근거\n\n${sentinel}\n\n| 항목 | 결과 |\n| --- | --- |\n| 판단 | 매수 보류 |`)
  await save.click()
  await expect(editor).toBeHidden()
  const row = page.getByRole('listitem').filter({ hasText: title }).first()
  await expect(row).toContainText(summary)
  await expect(row).not.toContainText(sentinel)
  for (const width of [360, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    const bounds = await row.boundingBox()
    expect(bounds.x).toBeGreaterThanOrEqual(0)
    expect(bounds.x + bounds.width).toBeLessThanOrEqual(width)
    const role = await row.locator('.type-secondary').evaluate((element) => {
      const style = getComputedStyle(element)
      return { size: style.fontSize, clamp: style.webkitLineClamp }
    })
    expect(role.clamp).toBe('3')
    expect(parseFloat(role.size)).toBeGreaterThanOrEqual(14)
  }
  await row.getByRole('button', { name: `기록 보기: ${title}` }).click()
  const detail = page.getByRole('dialog', { name: '기록 상세' })
  await expect(detail.getByText(summary, { exact: true })).toBeVisible()
  await expect(detail.getByRole('heading', { name: '상세 근거' })).toBeVisible()
  await expect(detail).toContainText(sentinel)
  await page.setViewportSize({ width: 390, height: 844 })
  await detail.screenshot({ path: test.info().outputPath('structured-detail-390.png') })
  await detail.getByRole('button', { name: '닫기', exact: true }).last().click()
  await page.getByRole('textbox', { name: '활동 검색' }).fill(sentinel)
  const result = page.getByRole('article').filter({ has: page.getByRole('heading', { name: title, exact: true }) })
  await expect(result).toBeVisible()
  await expect(result).toContainText(summary)
  await expect(result).not.toContainText(sentinel)
  await result.getByRole('button', { name: `기록 보기: ${title}` }).click()
  await detail.getByRole('button', { name: `기록 편집: ${title}` }).click()
  await detail.getByRole('textbox', { name: '요약', exact: true }).fill('조건 확정 이후 현금 확보를 우선하기로 결정했다.')
  await detail.getByRole('button', { name: '저장', exact: true }).click()
  await expect(detail.getByText('조건 확정 이후 현금 확보를 우선하기로 결정했다.', { exact: true })).toBeVisible()
})

test('keeps legacy body out of lists and records actual task completion results', async ({ page }) => {
  await signInAs(page, 'e2e-owner@example.com')
  const title = `E2E 기존 요약 없음 ${Date.now()}`
  const created = await callRpc(page, 'app_create_activity', {
    input_idempotency_key: crypto.randomUUID(), input_payload: { title, body: '기존본문노출금지-174', authored_via: 'app' },
  })
  expect(created.status).toBe(200)
  expect(created.body.summary).toBeNull()
  await page.goto('/#tasks')
  const legacy = page.getByRole('listitem').filter({ hasText: title }).first()
  await expect(legacy).toBeVisible()
  await expect(legacy).not.toContainText('기존본문노출금지-174')
  await clickPageAction(page, '할 일과 기록', '활동 추가')
  const taskTitle = `E2E 현금 확보 계획 ${Date.now()}`
  const editor = page.getByRole('dialog', { name: '활동 추가' })
  await editor.getByRole('textbox', { name: '할 일 제목' }).fill(taskTitle)
  await editor.getByRole('textbox', { name: '요약', exact: true }).fill('대출 상환 재원을 확인하고 매도 필요성을 판단한다.')
  await editor.getByLabel('할 일 본문').fill('대출 조건과 계좌별 현금을 대조한다. 계획본문전용-174')
  await editor.getByRole('button', { name: '저장', exact: true }).click()
  const task = page.getByRole('article').filter({ has: page.getByRole('button', { name: `할 일 보기: ${taskTitle}` }) })
  await expect(task).toContainText('대출 상환 재원을 확인하고 매도 필요성을 판단한다.')
  await expect(task).not.toContainText('계획본문전용-174')
  await task.getByRole('button', { name: `할 일 보기: ${taskTitle}` }).click()
  const taskDetail = page.getByRole('dialog', { name: '할 일 상세' })
  await expect(taskDetail.getByRole('textbox')).toHaveCount(0)
  await expect(taskDetail).toContainText('계획본문전용-174')
  await expect(taskDetail).toContainText('날짜 미정')
  for (const width of [320, 360, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    const titleStyle = await taskDetail.getByRole('heading', { name: taskTitle, exact: true }).evaluate((element) => {
      const style = getComputedStyle(element)
      const bounds = element.getBoundingClientRect()
      return { size: style.fontSize, weight: style.fontWeight, lineHeight: style.lineHeight, right: bounds.right }
    })
    expect(titleStyle).toMatchObject({ size: '24px', weight: '600', lineHeight: '32px' })
    expect(titleStyle.right).toBeLessThanOrEqual(width)
    expect(await taskDetail.getByRole('article').evaluate((element) => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1)
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await taskDetail.screenshot({ path: test.info().outputPath('task-document-390.png') })
  await page.setViewportSize({ width: 1440, height: 900 })
  await taskDetail.screenshot({ path: test.info().outputPath('task-document-1440.png') })
  await taskDetail.getByRole('button', { name: '닫기', exact: true }).last().click()
  await expect(task.getByRole('button', { name: `할 일 보기: ${taskTitle}` })).toBeFocused()
  await task.getByRole('button', { name: '완료', exact: true }).click()
  const completion = page.getByRole('dialog', { name: '할 일 완료' })
  await expect(completion.getByRole('button', { name: '완료 기록 저장' })).toBeDisabled()
  await completion.getByLabel('결과 제목').fill('대출 조건 미확정으로 매수 보류')
  await completion.getByLabel('결과 요약').fill('대출 일정이 미확정이라 추가 매수를 보류했다.')
  await expect(completion.getByRole('button', { name: '완료 기록 저장' })).toBeDisabled()
  await completion.getByLabel('결과 본문').fill('확인한 공식 자료와 미확인 대출 조건을 기록했다. 결과본문전용-174')
  await page.setViewportSize({ width: 390, height: 844 })
  await completion.screenshot({ path: test.info().outputPath('completion-390.png') })
  await completion.getByRole('button', { name: '완료 기록 저장' }).click()
  await expect(completion).toBeHidden()
  const result = page.getByRole('listitem').filter({ hasText: '대출 조건 미확정으로 매수 보류' }).first()
  await expect(result).toContainText('대출 일정이 미확정이라 추가 매수를 보류했다.')
  await expect(result).not.toContainText('결과본문전용-174')
  await expect(page.getByRole('button', { name: `할 일 보기: ${taskTitle}` })).toHaveCount(0)
})

test('clamps a long upper summary and keeps enlarged reading within the viewport', async ({ page }) => {
  await signInAs(page, 'e2e-owner@example.com')
  const title = `E2E 긴 요약 ${Date.now()}`
  const summary = '상환에 필요한 현금을 확보하기 전에는 추가 매수를 보류한다. '.repeat(7) + '긴문구'.repeat(15)
  const created = await callRpc(page, 'app_create_structured_activity', {
    input_idempotency_key: crypto.randomUUID(), input_payload: { title, summary, body: '목록에 노출하지 않을 상세 내용', authored_via: 'app' },
  })
  expect(created.status, JSON.stringify(created.body)).toBe(200)
  await page.goto('/#tasks')
  const row = page.getByRole('listitem').filter({ hasText: title }).first()
  for (const width of [360, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await expect(row).toContainText(summary)
    const layout = await row.locator('.type-secondary').evaluate((element) => {
      const rect = element.getBoundingClientRect()
      return { right: rect.right, height: rect.height, lineHeight: parseFloat(getComputedStyle(element).lineHeight) }
    })
    expect(layout.right).toBeLessThanOrEqual(width)
    expect(layout.height).toBeLessThanOrEqual(layout.lineHeight * 3 + 1)
  }
  await page.setViewportSize({ width: 780, height: 1200 })
  await page.evaluate(() => { document.documentElement.style.zoom = '2' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await row.getByRole('button', { name: `기록 보기: ${title}` }).click()
  const detail = page.getByRole('dialog', { name: '기록 상세' })
  await expect(detail.getByText(summary, { exact: true })).toBeVisible()
  await expect(detail.getByRole('button', { name: '닫기', exact: true }).last()).toBeInViewport()
  await page.evaluate(() => { document.documentElement.style.zoom = '' })
  await detail.getByRole('button', { name: '닫기', exact: true }).last().click()
  await expect(row.getByRole('button', { name: `기록 보기: ${title}` })).toBeFocused()
})
