create table public.product_feedback_admin_events (
  id bigint generated by default as identity primary key,
  feedback_id uuid not null references public.product_feedback(id) on delete cascade,
  admin_user_id uuid not null references auth.users(id) on delete restrict,
  before_state jsonb not null,
  after_state jsonb not null,
  created_at timestamptz not null default now()
);

create index product_feedback_admin_events_feedback_idx
  on public.product_feedback_admin_events (feedback_id, created_at desc, id desc);

alter table public.product_feedback_admin_events enable row level security;

create or replace function public.app_list_product_feedback_admin(
  input_cursor jsonb default null,
  input_limit integer default 20,
  input_status text default null
)
returns jsonb
language plpgsql
security definer
stable
set search_path = public, auth
as $$
declare
  page_limit integer := least(greatest(coalesce(input_limit, 20), 1), 50);
  cursor_updated_at timestamptz;
  cursor_id uuid;
  normalized_status text := nullif(btrim(coalesce(input_status, '')), '');
  result jsonb;
begin
  if auth.uid() is null or not public.app_is_product_feedback_admin() then
    raise exception 'feedback administrator access required';
  end if;

  if normalized_status is not null
     and normalized_status not in ('received', 'reviewing', 'planned', 'resolved', 'deferred') then
    raise exception 'invalid feedback status filter';
  end if;

  if input_cursor is not null then
    if jsonb_typeof(input_cursor) <> 'object'
       or not (input_cursor ? 'updated_at')
       or not (input_cursor ? 'id') then
      raise exception 'invalid feedback admin cursor';
    end if;
    cursor_updated_at := (input_cursor ->> 'updated_at')::timestamptz;
    cursor_id := (input_cursor ->> 'id')::uuid;
  end if;

  with page_rows as (
    select feedback.*
    from public.product_feedback as feedback
    where (normalized_status is null or feedback.status = normalized_status)
      and (
        cursor_updated_at is null
        or (feedback.updated_at, feedback.id) < (cursor_updated_at, cursor_id)
      )
    order by feedback.updated_at desc, feedback.id desc
    limit page_limit + 1
  ), visible_rows as (
    select *
    from page_rows
    order by updated_at desc, id desc
    limit page_limit
  )
  select jsonb_build_object(
    'items', coalesce(jsonb_agg(
      jsonb_build_object(
        'id', visible.id,
        'reporter_user_id', visible.reporter_user_id,
        'body', visible.body,
        'source', visible.source,
        'context', visible.context,
        'status', visible.status,
        'response', visible.response,
        'github_issue_url', visible.github_issue_url,
        'version', visible.version,
        'created_at', visible.created_at,
        'updated_at', visible.updated_at
      ) order by visible.updated_at desc, visible.id desc
    ), '[]'::jsonb),
    'next_cursor', case
      when (select count(*) from page_rows) > page_limit then (
        select jsonb_build_object('updated_at', tail.updated_at, 'id', tail.id)
        from visible_rows as tail
        order by tail.updated_at asc, tail.id asc
        limit 1
      )
      else null
    end
  )
  into result
  from visible_rows as visible;

  return coalesce(result, jsonb_build_object('items', '[]'::jsonb, 'next_cursor', null));
end;
$$;

create or replace function public.app_update_product_feedback_admin(
  input_feedback_id uuid,
  input_expected_version integer,
  input_status text,
  input_response text default null,
  input_github_issue_url text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  current_admin_id uuid := auth.uid();
  current_feedback public.product_feedback%rowtype;
  updated_feedback public.product_feedback%rowtype;
  normalized_response text := nullif(btrim(coalesce(input_response, '')), '');
  normalized_issue_url text := nullif(btrim(coalesce(input_github_issue_url, '')), '');
begin
  if current_admin_id is null or not public.app_is_product_feedback_admin() then
    raise exception 'feedback administrator access required';
  end if;

  if input_status not in ('received', 'reviewing', 'planned', 'resolved', 'deferred') then
    raise exception 'invalid feedback status';
  end if;

  if normalized_response is not null and char_length(normalized_response) > 4000 then
    raise exception 'feedback response must be at most 4000 characters';
  end if;

  if input_status = 'resolved' and normalized_response is null then
    raise exception 'resolved feedback requires a response';
  end if;

  if normalized_issue_url is not null
     and normalized_issue_url !~ '^https://github[.]com/[^/[:space:]]+/[^/[:space:]]+/issues/[0-9]+$' then
    raise exception 'github issue URL must be a canonical HTTPS issue URL';
  end if;

  select *
  into current_feedback
  from public.product_feedback
  where id = input_feedback_id
  for update;

  if not found then
    raise exception 'feedback not found';
  end if;

  if current_feedback.version <> input_expected_version then
    raise exception 'feedback version conflict';
  end if;

  update public.product_feedback
  set status = input_status,
      response = normalized_response,
      github_issue_url = normalized_issue_url,
      version = version + 1,
      updated_at = now()
  where id = input_feedback_id
  returning * into updated_feedback;

  insert into public.product_feedback_admin_events (
    feedback_id,
    admin_user_id,
    before_state,
    after_state
  ) values (
    current_feedback.id,
    current_admin_id,
    jsonb_build_object(
      'status', current_feedback.status,
      'response', current_feedback.response,
      'github_issue_url', current_feedback.github_issue_url,
      'version', current_feedback.version
    ),
    jsonb_build_object(
      'status', updated_feedback.status,
      'response', updated_feedback.response,
      'github_issue_url', updated_feedback.github_issue_url,
      'version', updated_feedback.version
    )
  );

  return jsonb_build_object(
    'id', updated_feedback.id,
    'reporter_user_id', updated_feedback.reporter_user_id,
    'body', updated_feedback.body,
    'source', updated_feedback.source,
    'context', updated_feedback.context,
    'status', updated_feedback.status,
    'response', updated_feedback.response,
    'github_issue_url', updated_feedback.github_issue_url,
    'version', updated_feedback.version,
    'created_at', updated_feedback.created_at,
    'updated_at', updated_feedback.updated_at
  );
end;
$$;

revoke all on function public.app_list_product_feedback_admin(jsonb, integer, text) from public, anon;
revoke all on function public.app_update_product_feedback_admin(uuid, integer, text, text, text) from public, anon;

grant execute on function public.app_list_product_feedback_admin(jsonb, integer, text) to authenticated;
grant execute on function public.app_update_product_feedback_admin(uuid, integer, text, text, text) to authenticated;
