-- The remote history starts with placeholder migrations, while the first
-- substantive migration already assumes these legacy portfolio tables exist.
-- Keep this idempotent so fresh local resets can replay the full history.

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  name text not null,
  color text not null default 'neutral',
  sort_order integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, name)
);

create table if not exists public.instruments (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  ticker text not null,
  display_name text not null,
  instrument_type text not null default 'market',
  currency text not null default 'KRW',
  price_source text default 'manual',
  source_symbol text,
  note text,
  updated_at timestamptz default now(),
  unique (user_id, ticker)
);

create table if not exists public.instrument_tags (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  ticker text not null,
  tag_id bigint not null references public.tags(id) on delete cascade,
  created_at timestamptz default now()
);

create table if not exists public.holding_prices_daily (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  ticker text not null,
  price_date date not null,
  close_price real not null,
  source text default 'manual',
  created_at timestamptz default now(),
  unique (user_id, ticker, price_date)
);

create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  name text not null,
  broker text,
  note text,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, name)
);

create table if not exists public.holdings (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  account_id bigint not null references public.accounts(id) on delete cascade,
  ticker text not null,
  quantity real,
  avg_price real,
  purchase_amount numeric,
  valuation_amount numeric,
  note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (account_id, ticker)
);
